apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifi
  labels:
    app: notifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifi
  template:
    metadata:
      labels:
        app: notifi
    spec:
      containers:
        - name: notifi
          image: username/notifi:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5